# NUMPY

In [1]:
import numpy as np

# DataType & Attributes

# NP.ARRAY

* Create an array

In [2]:
al =np.array([1,2,3])
al

array([1, 2, 3])

# TYPE

* type(object) -> the object's type

In [3]:
type(al)

numpy.ndarray

In [4]:
a2= np.array([[1,2,3],[12,32,34]])
a2

array([[ 1,  2,  3],
       [12, 32, 34]])

In [5]:
al.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
# demison
al.ndim

1

In [8]:
a2.ndim

2

In [9]:
a2.dtype

dtype('int32')

In [10]:
al.size

3

In [11]:
a2.size

6

In [12]:
type(al),type(a2)

(numpy.ndarray, numpy.ndarray)

In [13]:
# create a DataFrame from a numpy array
import pandas as pd
df = pd.DataFrame(a2)

In [14]:
df

0   1   2
0   1   2   3
1  12  32  34

In [15]:
type(df)

pandas.core.frame.DataFrame

## creating array

In [16]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

# NP.ONES

* Return a new array of given shape and type, filled with ones

In [17]:
ones =np.ones((5,5) ,dtype=str)
ones

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [18]:
ones.dtype

dtype('<U1')

# NP.ZEROS

* Return a new array of given shape and type, filled with zeros

In [19]:
zeros = np.zeros((5,5),dtype=str)
zeros

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [20]:
zeros.dtype

dtype('<U1')

# NP.ARANGE

* Return evenly spaced values within a given interval

In [21]:
rangeArray =np.arange(1,10,1)
rangeArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
twoDeArray =np.array([rangeArray,rangeArray*2])
twoDeArray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [23]:
threeDeArray = np.array([rangeArray,rangeArray*2,rangeArray*3])
threeDeArray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27]])

## NP.RANDOM.RANDINT

* Return random integers from `low` (inclusive) to `high` (exclusive)

In [24]:
randomArray =np.random.randint(0,10,size=(2,3,4,5),dtype=int)
randomArray

array([[[[1, 4, 0, 4, 8],
         [8, 2, 9, 4, 1],
         [8, 3, 2, 4, 5],
         [1, 2, 6, 8, 4]],

        [[8, 5, 4, 3, 2],
         [1, 2, 2, 0, 4],
         [7, 5, 4, 0, 8],
         [8, 2, 3, 2, 4]],

        [[6, 5, 0, 4, 4],
         [7, 4, 0, 1, 2],
         [7, 4, 4, 0, 0],
         [7, 5, 9, 0, 7]]],


       [[[6, 3, 6, 8, 3],
         [6, 5, 5, 1, 4],
         [1, 9, 8, 0, 6],
         [3, 2, 1, 4, 3]],

        [[9, 6, 5, 6, 2],
         [5, 7, 9, 4, 2],
         [0, 5, 5, 4, 1],
         [5, 0, 1, 9, 8]],

        [[0, 6, 9, 9, 2],
         [3, 4, 8, 0, 4],
         [7, 6, 2, 4, 3],
         [5, 6, 5, 9, 7]]]])

In [25]:
randomArray.size

120

In [26]:
randomArray.shape

(2, 3, 4, 5)

In [27]:
randomArray.dtype

dtype('int32')

## NP.RANDOM.RANDOM

* Return random floats in the half-open interval [0.0, 1.0)

In [28]:
np.random.random((2,2))

array([[0.86482812, 0.24906281],
       [0.51829511, 0.23987053]])

In [29]:
#Pseudo-random number
np.random.seed(seed=0)
rr=np.random.randint(5,10,size=(5,4))
rr

array([[9, 5, 8, 8],
       [8, 6, 8, 7],
       [9, 5, 5, 9],
       [7, 6, 5, 6],
       [6, 5, 6, 9]])

# Viewing arrays and Matrices

### NP.UNIQUE

* Returns the sorted unique elements of an array

In [30]:
np.unique(rr)

array([5, 6, 7, 8, 9])

In [31]:
al

array([1, 2, 3])

In [32]:
al[0],al[2]

(1, 3)

In [33]:
threeDeArray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [34]:
threeDeArray[0][3]

4

In [35]:
threeDeArray[0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
threeDeArray[:2]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [37]:
threeDeArray[:2,:2]

array([[1, 2],
       [2, 4]])

In [38]:
threeDeArray[:2,:3]

array([[1, 2, 3],
       [2, 4, 6]])

In [39]:
randomArray

array([[[[1, 4, 0, 4, 8],
         [8, 2, 9, 4, 1],
         [8, 3, 2, 4, 5],
         [1, 2, 6, 8, 4]],

        [[8, 5, 4, 3, 2],
         [1, 2, 2, 0, 4],
         [7, 5, 4, 0, 8],
         [8, 2, 3, 2, 4]],

        [[6, 5, 0, 4, 4],
         [7, 4, 0, 1, 2],
         [7, 4, 4, 0, 0],
         [7, 5, 9, 0, 7]]],


       [[[6, 3, 6, 8, 3],
         [6, 5, 5, 1, 4],
         [1, 9, 8, 0, 6],
         [3, 2, 1, 4, 3]],

        [[9, 6, 5, 6, 2],
         [5, 7, 9, 4, 2],
         [0, 5, 5, 4, 1],
         [5, 0, 1, 9, 8]],

        [[0, 6, 9, 9, 2],
         [3, 4, 8, 0, 4],
         [7, 6, 2, 4, 3],
         [5, 6, 5, 9, 7]]]])

In [40]:
randomArray[:,:,:,:2]

array([[[[1, 4],
         [8, 2],
         [8, 3],
         [1, 2]],

        [[8, 5],
         [1, 2],
         [7, 5],
         [8, 2]],

        [[6, 5],
         [7, 4],
         [7, 4],
         [7, 5]]],


       [[[6, 3],
         [6, 5],
         [1, 9],
         [3, 2]],

        [[9, 6],
         [5, 7],
         [0, 5],
         [5, 0]],

        [[0, 6],
         [3, 4],
         [7, 6],
         [5, 6]]]])

In [41]:
randomArray[:,:,:2,:2]


array([[[[1, 4],
         [8, 2]],

        [[8, 5],
         [1, 2]],

        [[6, 5],
         [7, 4]]],


       [[[6, 3],
         [6, 5]],

        [[9, 6],
         [5, 7]],

        [[0, 6],
         [3, 4]]]])

In [42]:
randomArray[:,:2,:2,:2]

array([[[[1, 4],
         [8, 2]],

        [[8, 5],
         [1, 2]]],


       [[[6, 3],
         [6, 5]],

        [[9, 6],
         [5, 7]]]])

In [43]:
randomArray[:1,:2,:2,:2]

array([[[[1, 4],
         [8, 2]],

        [[8, 5],
         [1, 2]]]])

## Manipulation &Comparing arrays

### Arithmetic

In [44]:
al

array([1, 2, 3])

In [45]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [46]:
al+ones

array([2., 3., 4.])

In [47]:
al*ones

array([1., 2., 3.])

In [48]:
al-ones

array([0., 1., 2.])

### Aggregation

In [49]:
al

array([1, 2, 3])

In [50]:
np.sum(al)

6

### Use Python method (`sum()`) on python datatypes and use Numpy method on numpy arrays(`np.sum()`).

In [51]:
# create a massive Numpy array
massiveArray =np.random.random(1000)
massiveArray[:10]

array([0.0202184 , 0.83261985, 0.77815675, 0.87001215, 0.97861834,
       0.79915856, 0.46147936, 0.78052918, 0.11827443, 0.63992102])

In [52]:
%timeit sum(massiveArray) # python sum

364 µs ± 25.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [53]:
%timeit np.sum(massiveArray) #numpy sum

20.5 µs ± 1.41 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [54]:
np.mean(massiveArray)

0.4930979202769521

In [55]:
np.max(massiveArray)

0.9998085781169653

In [56]:
np.min(massiveArray)

0.0005459648969956543

In [57]:
np.std(massiveArray)

0.29139085073090576

In [58]:
# Variance =measure of yhe average degree to which each number is different to the mean 
# higher variance = wider range of numbers
#lower variance =lower range of numbers

np.var(massiveArray)

0.084908627889681

In [59]:
# Demo of std and var
highVarArray =np.array([1,100,200,300,4000,5000])
lowVarArray=np.array([2,4,6,8,10])

In [60]:
np.var(highVarArray),np.var(lowVarArray)

(4296133.472222221, 8.0)

In [61]:
np.std(highVarArray),np.std(lowVarArray)

(2072.711623024829, 2.8284271247461903)

In [62]:
np.mean(highVarArray),np.mean(lowVarArray)

(1600.1666666666667, 6.0)

In [63]:
%matplotlib
from matplotlib import pyplot as plt
plt.hist(highVarArray)


Using matplotlib backend: <object object at 0x0000014620FBD710>


(array([4., 0., 0., 0., 0., 0., 0., 1., 0., 1.]),
 array([1.0000e+00, 5.0090e+02, 1.0008e+03, 1.5007e+03, 2.0006e+03,
        2.5005e+03, 3.0004e+03, 3.5003e+03, 4.0002e+03, 4.5001e+03,
        5.0000e+03]),
 <BarContainer object of 10 artists>)

In [64]:
plt.hist(lowVarArray)

(array([1., 0., 1., 0., 0., 1., 0., 1., 0., 1.]),
 array([ 2. ,  2.8,  3.6,  4.4,  5.2,  6. ,  6.8,  7.6,  8.4,  9.2, 10. ]),
 <BarContainer object of 10 artists>)

### Reshaping & Transposing

In [65]:
a2=np.array([[2,3,4,5,6,7,8,9],
            [4,5,6,7,1,2,3,4]])
a2

array([[2, 3, 4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 1, 2, 3, 4]])

In [66]:
twoDeArray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [67]:
twoDeArray.shape

(2, 9)

In [68]:
al.reshape(3,1)

array([[1],
       [2],
       [3]])

In [69]:
threeDeArray


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [70]:
al.reshape(3,1)*threeDeArray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [71]:
threeDeArray

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27]])

In [72]:
threeDeArray.T

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18],
       [ 7, 14, 21],
       [ 8, 16, 24],
       [ 9, 18, 27]])

## Dot product

In [73]:
np.random.seed(0)
mat1 =np.random.randint(10,size=(5,3))
mat2 =np.random.randint(10,size=(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [74]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [75]:
mat1 *mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [76]:
np.dot(mat1.T,mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

## Dot product example

In [77]:
np.random.seed(0)
salesAmount =np.random.randint(20,size=(6,3))
salesAmount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7],
       [14, 17,  5]])

In [78]:
weekySales=pd.DataFrame(salesAmount,index=["mon","tues","wed","thus","fri","sat"],
                       columns=["Almond butter","Peanut","cashew"])
weekySales

Almond butter  Peanut  cashew
mon              12      15       0
tues              3       3       7
wed               9      19      18
thus              4       6      12
fri               1       6       7
sat              14      17       5

In [79]:
weekySales.to_csv("weeky-Sales")

In [80]:
prices=np.array([12,21,34])
prices

array([12, 21, 34])

# Reshape

* Returns an array containing the same data with a new shape.

In [81]:
butterPrices=pd.DataFrame(prices.reshape(1,3),index=["price"],columns=["Almond butter","Peanut","cashew"])
butterPrices

Almond butter  Peanut  cashew
price             12      21      34

In [82]:
totalPrice =prices.dot(salesAmount.T)
totalPrice

array([ 459,  337, 1119,  582,  376,  695])

In [83]:
butterPrices

Almond butter  Peanut  cashew
price             12      21      34

In [84]:
weekySales

Almond butter  Peanut  cashew
mon              12      15       0
tues              3       3       7
wed               9      19      18
thus              4       6      12
fri               1       6       7
sat              14      17       5

In [85]:
dailySales =butterPrices.dot(weekySales.T)
dailySales

mon  tues   wed  thus  fri  sat
price  459   337  1119   582  376  695

In [86]:
weekySales["Total"] =dailySales.T
weekySales

Almond butter  Peanut  cashew  Total
mon              12      15       0    459
tues              3       3       7    337
wed               9      19      18   1119
thus              4       6      12    582
fri               1       6       7    376
sat              14      17       5    695

### Comparison Operator

In [87]:
a2=np.array([[12,3,4],[5,17,8]])
a2,al

(array([[12,  3,  4],
        [ 5, 17,  8]]),
 array([1, 2, 3]))

In [88]:
 al>=a2

array([[False, False, False],
       [False, False, False]])

In [89]:
al>2

array([False, False,  True])

In [90]:
al==a2

array([[False, False, False],
       [False, False, False]])

# Sorting

In [91]:
a2

array([[12,  3,  4],
       [ 5, 17,  8]])

## NP.SORT

* Return a sorted copy of an array

In [92]:
np.sort(a2)

array([[ 3,  4, 12],
       [ 5,  8, 17]])

## NP.ARGSORT

* Returns the indices that would sort an array

In [93]:
np.argsort(a2)

array([[1, 2, 0],
       [0, 2, 1]], dtype=int64)

## NP.ARGMAX

* Returns the indices of the maximum values along an axis

In [94]:
# col
np.argmax(a2,axis=0)

array([0, 1, 1], dtype=int64)

In [95]:
#row
np.argmax(a2,axis=1)

array([0, 1], dtype=int64)

# Practical Example 

In [96]:
%%HTML
<img src="images/panda.png"  height=10 width=200/>

## IMREAD

* Read an image from a file into an array

In [97]:
# Turn image into Numpy 
%matplotlib
from matplotlib.image import imread

panda =imread("images/panda.png")
panda

Using matplotlib backend: QtAgg


array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [98]:
panda.size,panda.shape

(24465000, (2330, 3500, 3))

In [99]:
panda[2][3]

array([0.05490196, 0.10588235, 0.06666667], dtype=float32)

In [100]:
panda[:]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [101]:
type(panda)

numpy.ndarray

In [102]:
from PIL import Image

In [103]:
w,h=512,512
data =np.zeros((w,h,3),dtype=np.uint8)
img =Image.fromarray(data,"RGB")
img.show()

In [104]:
w,h=512,512
data =np.ones((w,h,3),dtype=np.uint8)
img =Image.fromarray(data,"RGB")
img.show()